### ISSUE TITLE
Add support for orphan_file and metadata_csum features

### ISSUE THREAD

**Issue by rgayon** [libyal/libfsext#13]
This feature was enabled by default in e2fsprogs mkfs [version 1.47.0 ](https://e2fsprogs.sourceforge.net/e2fsprogs-release.html)

Some OS have decided to disable it later in their packagings, for example Ubuntu enabled orphan_file in e2fsprogs (1.47.0-1) on 23.04, and then disabled it "temporarily" in 1.47.0-1ubuntu2, and then "definitely"  in 1.47.0-2 for 23.10

**Comment by rgayon** [comment]
On a FS with this feature enabled, such as displayed here:

```
$ sudo tune2fs -l /dev/sda1 | grep features
Filesystem features:      has_journal ext_attr resize_inode dir_index orphan_file filetype extent 64bit flex_bg sparse_super large_file huge_file dir_nlink extra_isize metadata_csum
```
using this library to parse the filesystem's partitions will lead to error:
`libfsext_superblock_read_data: unsupported compatible features flags: 0x0000103c. `

**Comment by joachimmetz** [comment]
Looks like there are a couple more related flags e.g. EXT4_FEATURE_RO_COMPAT_ORPHAN_PRESENT https://elixir.bootlin.com/linux/latest/source/fs/ext4/ext4.h 

Also metadata_csum is currently not supported

I'll have a look when time permits

**Comment by joachimmetz** [comment]
Was able to create file system with the flag using `mke2fs -E orphan_file_size=#` per documentation found so far looks like this flag controls the use of the orphan file (s_orphan_file_inum) instead of the orphan list.

**Comment by joachimmetz** [comment]
Basic support was added, closing issue
