### ISSUE TITLE
Have fsextinfo output bodyfile to stdout

### ISSUE THREAD

**Issue by rgayon** [libyal/libfsext#6]
have `-B -` output the mactime to stdout instead of a file for scripting.

**Comment by joachimmetz** [comment]
The reason why this is currently not done is the pre-amble with the version being output to stdout

**Comment by joachimmetz** [comment]
Also let chat about your use case here, a dfVFS based script under https://github.com/log2timeline/imagetools might be more general purpose. For now fsextinfo has largely been intended for testing and troubleshooting.

**Comment by joachimmetz** [comment]
use case: ability to script a quick-and-dirty export to bodyfile and grep it for filename/path approach

**Comment by joachimmetz** [comment]
Closing this in favor of https://github.com/log2timeline/dfimagetools
